version: '3.8'

services:
  medicine-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
    # env_file:
    #   - .env
    # command: npm run dev 
